prefix ns1: <http://schema.org/> 
prefix ns2: <https://dbpedia.org/ontology/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?note
WHERE {
    ?rest ns1:name ?name .
    ?rest ns1:aggregateRating ?note .
    ?rest ns1:servesCuisine ?cuisine .
    ?rest ns1:paymentAccepted ?paymentAccepted .
    FILTER(?note > 4 && contains(?cuisine, "végétarien"))
}