prefix ns1: <https://schema.org/> 
prefix ns2: <https://dbpedia.org/ontology/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix example: <https://www.example.org/>

# Les restaurants crous qui sont des caféterias accessible en bus
SELECT ?identifier ?name
WHERE {
    ?rest ns1:identifier ?identifier .
    ?rest ns1:name ?name .
    ?rest example:typeCrous "Cafétéria" .
    ?rest ns1:description ?description . 
    FILTER contains(?description,"bus")
}