prefix ns1: <https://schema.org/> 
prefix ns2: <https://dbpedia.org/ontology/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix example: <https://www.example.org/>

# Les restaurants du crous qui possèdent un point de contact qui contient Paris dans son adresse.

SELECT ?name
WHERE {
    ?rest ns1:name ?name .
    ?rest ns1:ContactPoint ?contact .
    ?contact ns1:description ?description .
    FILTER(contains(?description, "Paris"))
}