prefix ns1: <https://schema.org/> 
prefix ns2: <https://dbpedia.org/ontology/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix example: <https://www.example.org/>

# Les restaurants du crous qui sont dans la zone de Nantes et qui accepte les paiements IZLY.

SELECT ?identifier ?name
WHERE {
    ?rest ns1:identifier ?identifier .
    ?rest ns1:name ?name .
    ?rest example:zone ?zone .
    ?rest ns1:description ?description .
    FILTER(contains(?zone,"Nantes") && contains(?description, "IZLY"))
}